In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

# model = MultinomialNB()
model = BernoulliNB()
# model = GaussianNB()

In [3]:
data = pd.read_csv('dataset/flight-weather.csv')
# data.keys()

# BernoulliNB

In [37]:
# drop some useless and cant handle data
X = data.drop([ 'arr_delay', 'arr_time', 'minute', 'HOURLYStationPressure', 'carrier', 'tailnum', 'dest'], axis = 1)

#### Normalise the data

In [76]:
Y = pd.read_csv('dataset/flight-weather.csv', usecols=['arr_delay'])
y = np.ravel(Y)

In [90]:
from sklearn import preprocessing
preprocessing.MinMaxScaler().fit(X)
preprocessing.StandardScaler().fit(X)

StandardScaler()

In [39]:
# classify
for i in y:
    if(i <= 0):
        y[i] = 0;
    else:
        y[i] = 1;
        
for v in range(len(y)):
    if(X['origin'][v] == 'LGA'):
        X['origin'][v] = 0;
    elif(X['origin'][v] == 'EWR'):
        X['origin'][v] = 1;
    else:
        X['origin'][v] = 2;

##### Cross Validation with Bernoulli

In [91]:
from sklearn.model_selection import cross_val_score
from statistics import mean
mean(cross_val_score(model, X, y, cv=10, scoring="accuracy", n_jobs=10))

0.02929580072494807

In [92]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.3, random_state = 101)

In [93]:
model.fit(train_X, train_y)

BernoulliNB()

In [95]:
model.predict(train_X)

array([-13, -13, -13, ..., -13,   1,   1])

In [22]:
from sklearn.base import BaseEstimator 
class Estimator (BaseEstimator): 
    def fit (self, X, y = None):
        #Accept input data, X, and optional target data, y. Returns self.'''
        return self
    def predict(self, X):
        #Accept input data, X and return a vector of predictions for each row.'''
        return yhat
    
    
from sklearn.base import TransformerMixin
class Transfomer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        #Learn how to transform data based on input data, X.'''
        return self
    def transform(self, X):
        #Transform X into a new dataset, Xprimeand return it.'''
        return Xprime

## KNN

In [65]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier()


KNeighborsClassifier()

In [97]:
X = pd.read_csv('dataset/flight-weather.csv', usecols=['dep_delay', 'distance'])

for i in y:
    if(i <= 0):
        y[i] = 0;
    else:
        y[i] = 1;

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.3, random_state = 101)
knn.fit(X, y)

KNeighborsClassifier()

In [100]:
model.predict(test_X)

array([-13, -13, -13, ..., -13,   1,   1])

dep_delay  distance
24450         -3      1096
15353         -6      1389
4635          -5       184
30754         -6       746
9244          25      1096
...          ...       ...
27668          2       711
27331         -5      1372
10306         -3      2475
23309          6      1020
29437         29       431

[9821 rows x 2 columns]

In [81]:
knn.score(test_X, test_y, sample_weight=None)

0.1471336931066083

In [82]:
y

array([0, 1, 1, ..., 0, 0, 0])